export const routes = [
  { path: 'accordion', loadChildren: './accordion/accordion.module#NglDemoAccordionModule' },
  { path: 'alert', loadChildren: './alert/alert.module#NglDemoAlertModule' },
  { path: 'avatar', loadChildren: './avatar/avatar.module#NglDemoAvatarModule' },
  { path: 'badges', loadChildren: './badges/badges.module#NglDemoBadgesModule' },
  { path: 'breadcrumbs', loadChildren: './breadcrumbs/breadcrumbs.module#NglDemoBreadcrumbsModule' },
  { path: 'button-icons', loadChildren: './button-icons/button-icons.module#NglDemoButtonIconsModule', label: 'Button Icons' },
  { path: 'buttons', loadChildren: './buttons/buttons.module#NglDemoButtonsModule' },
  { path: 'carousel', loadChildren: './carousel/carousel.module#NglDemoCarouselModule' },
  { path: 'checkboxes', loadChildren: './checkboxes/checkboxes.module#NglDemoCheckboxesModule' },
  { path: 'colorpicker', loadChildren: './colorpicker/colorpicker.module#NglDemoColorpickerModule' },
  { path: 'comboboxes', loadChildren: './comboboxes/comboboxes.module#NglDemoComboboxesModule' },
  { path: 'datatables', loadChildren: './datatables/datatables.module#NglDemoDatatablesModule' },
  { path: 'datepickers', loadChildren: './datepickers/datepickers.module#NglDemoDatepickersModule' },
  { path: 'dynamicicons', loadChildren: './dynamicicons/dynamicicons.module#NglDemoDynamicIconsModule', label: 'Dynamic Icons' },
  { path: 'files', loadChildren: './files/files.module#NglDemoFilesModule' },
  { path: 'file-upload', loadChildren: './file-upload/file-upload.module#NglDemoFileUploadModule', label: 'File Selector' },
  { path: 'icons', loadChildren: './icons/icons.module#NglDemoIconsModule' },
  { path: 'input', loadChildren: './input/input.module#NglDemoInputModule' },
  { path: 'lookups', loadChildren: './lookups/lookups.module#NglDemoLookupsModule' },
  { path: 'menus', loadChildren: './menus/menus.module#NglDemoMenusModule' },
  { path: 'modals', loadChildren: './modals/modals.module#NglDemoModalsModule' },
  { path: 'paginations', loadChildren: './paginations/paginations.module#NglDemoPaginationsModule' },
  { path: 'pick', loadChildren: './pick/pick.module#NglDemoPickModule' },
  { path: 'picklist', loadChildren: './picklist/picklist.module#NglDemoPicklistModule' },
  { path: 'pills', loadChildren: './pills/pills.module#NglDemoPillsModule' },
  { path: 'popovers', loadChildren: './popovers/popovers.module#NglDemoPopoversModule' },
  { path: 'progressbar', loadChildren: './progressbar/progressbar.module#NglDemoProgressBarModule', label: 'Progress Bar' },
  { path: 'prompt', loadChildren: './prompt/prompt.module#NglDemoPromptModule' },
  { path: 'radio-group', loadChildren: './radio-group/radio-group.module#NglDemoRadioGroupModule', label: 'Radio Group' },
  { path: 'ratings', loadChildren: './ratings/ratings.module#NglDemoRatingsModule' },
  { path: 'sections', loadChildren: './sections/sections.module#NglDemoSectionsModule' },
  { path: 'slider', loadChildren: './slider/slider.module#NglDemoSliderModule' },
  { path: 'select', loadChildren: './select/select.module#NglDemoSelectModule' },
  { path: 'spinners', loadChildren: './spinners/spinners.module#NglDemoSpinnersModule' },
  { path: 'tabs', loadChildren: './tabs/tabs.module#NglDemoTabsModule' },
  { path: 'textarea', loadChildren: './textarea/textarea.module#NglDemoTextareaModule' },
  { path: 'toast', loadChildren: './toast/toast.module#NglDemoToastModule' },
  { path: 'tooltips', loadChildren: './tooltips/tooltips.module#NglDemoTooltipsModule' },
];
